name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis relevance

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'  # Use any other distribution if required.

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build and run specific tests
      - name: Build and run specific tests
        working-directory: ./apis  # Ensure this points to where your `pom.xml` resides
        run: mvn -B clean test -Dtest=MenuCategoryControllerDiffblueTest

      - name: Run tests with coverage
        working-directory: ./apis  # Ensure this points to where your `pom.xml` resides
        run: mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=HiteshAsranii_RESTAURANTSB \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


      # SonarCloud analysis
      - name: SonarCloud analysis
        working-directory: ./apis  # Ensure this points to where your `pom.xml` resides
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # To retrieve PR details
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your SonarCloud token
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=HiteshAsranii_RESTAURANTSB
